version: "2"

linters:
  default: none
  enable:
    # Core
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Security
    - gosec

    # Quality
    - gocyclo
    - gocognit
    - funlen
    - goconst
    - dupl

    # Best Practices
    - gocritic
    - revive
    - misspell
    - whitespace
    - unparam
    - unconvert

  settings:
    cyclop:
      max-complexity: 30

    funlen:
      lines: 100
      statements: 50

    gocognit:
      min-complexity: 20

    gocyclo:
      min-complexity: 30

    goconst:
      min-len: 2
      min-occurrences: 3

    dupl:
      threshold: 100

    revive:
      enable-all-rules: false
      rules:
        # Critical rules
        - name: blank-imports
        - name: context-keys-type
        - name: time-equal
        - name: time-naming
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration

    gocritic:
      disabled-checks:
        - ifElseChain
        - commentFormatting
        - badCall

    godot:
      scope: declarations
      exclude:
        - "^@"
        - "^TODO"
        - "^FIXME"
        - "^BUG"

    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (*os.File).Close
        - (io.Closer).Close

    staticcheck:
      checks: ["all"]

    gosec:
      excludes:
        - G104  # Audit errors not checked (handled by errcheck)

  exclusions:
    generated: strict
    rules:
      # Exclude some linters from test files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
          - goconst
          - unparam
          - revive  # Allow dot imports and unused parameters in tests

      # Allow long functions in main.go (GitHub Actions handlers)
      - path: cmd/github-action/main\.go
        linters:
          - funlen
          - gocyclo
          - cyclop
          - gocognit

      # Exclude error shadowing in test setup
      - path: _test\.go
        text: "shadow: declaration of \"err\""
        linters:
          - govet

issues:
  max-same-issues: 50

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - tmp
    - bin
    - .git
