version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: smyklot
    main: ./cmd/github-action
    binary: smyklot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: smyklot
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

dockers_v2:
  - ids:
      - smyklot
    images:
      - ghcr.io/bartsmykla/smyklot
    tags:
      - "{{ trimprefix .Tag \"v\" }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - cmd
      - pkg
    labels:
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.description: "Automated PR approvals and merges based on CODEOWNERS"
      org.opencontainers.image.url: "https://github.com/bartsmykla/smyklot"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: MIT

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Smyklot {{.Tag}}

    Docker image: `ghcr.io/bartsmykla/smyklot:{{ trimprefix .Tag "v" }}`
