name: Smyklot PR Commands
description: GitHub Actions bot for automated PR approvals and merges based on CODEOWNERS
author: Bart Smykla

branding:
  icon: check-circle
  color: green

inputs:
  token:
    description: GitHub token for API authentication
    required: false
    default: ''
  comment-body:
    description: PR comment body text
    required: false
    default: ''
  comment-id:
    description: PR comment ID
    required: false
    default: ''
  pr-number:
    description: Pull request number
    required: false
    default: ''
  repo-owner:
    description: Repository owner
    required: false
    default: ''
  repo-name:
    description: Repository name
    required: false
    default: ''
  comment-author:
    description: Comment author username
    required: false
    default: ''
  config:
    description: Full configuration as JSON (overrides individual settings)
    required: false
    default: ''
  quiet-success:
    description: Disable success comments (emoji only)
    required: false
    default: ''
  allowed-commands:
    description: Allowed commands (comma-separated)
    required: false
    default: ''
  command-aliases:
    description: Command aliases as JSON
    required: false
    default: ''
  command-prefix:
    description: Custom command prefix
    required: false
    default: ''
  disable-mentions:
    description: Disable @smyklot mentions
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: ${{ github.action_path }}/go.mod
        cache-dependency-path: ${{ github.action_path }}/go.sum

    - name: Build smyklot binary
      shell: bash
      run: |
        cd ${{ github.action_path }} || exit 1
        go build -o ${{ runner.temp }}/smyklot-github-action ./cmd/github-action

    - name: Parse configuration
      id: parse-config
      shell: bash
      env:
        CONFIG_JSON: ${{ inputs.config }}
      run: |
        # If config JSON is provided, parse it and set outputs
        if [ -n "$CONFIG_JSON" ]; then
          {
            echo "quiet_success=$(echo "$CONFIG_JSON" | \
              jq -r '.quiet_success // empty')"
            echo "allowed_commands=$(echo "$CONFIG_JSON" | \
              jq -r '.allowed_commands // [] | join(",")')"
            echo "command_aliases=$(echo "$CONFIG_JSON" | \
              jq -c '.command_aliases // {}')"
            echo "command_prefix=$(echo "$CONFIG_JSON" | \
              jq -r '.command_prefix // empty')"
            echo "disable_mentions=$(echo "$CONFIG_JSON" | \
              jq -r '.disable_mentions // empty')"
          } >> "$GITHUB_OUTPUT"
        fi

    - name: Execute command
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token || env.GITHUB_TOKEN }}
        COMMENT_BODY: ${{ inputs.comment-body || env.COMMENT_BODY }}
        COMMENT_ID: ${{ inputs.comment-id || env.COMMENT_ID }}
        PR_NUMBER: ${{ inputs.pr-number || env.PR_NUMBER }}
        REPO_OWNER: ${{ inputs.repo-owner || env.REPO_OWNER }}
        REPO_NAME: ${{ inputs.repo-name || env.REPO_NAME }}
        COMMENT_AUTHOR: ${{ inputs.comment-author || env.COMMENT_AUTHOR }}
        SMYKLOT_QUIET_SUCCESS: >-
          ${{
            inputs.quiet-success ||
            env.SMYKLOT_QUIET_SUCCESS ||
            steps.parse-config.outputs.quiet_success
          }}
        SMYKLOT_ALLOWED_COMMANDS: >-
          ${{
            inputs.allowed-commands ||
            env.SMYKLOT_ALLOWED_COMMANDS ||
            steps.parse-config.outputs.allowed_commands
          }}
        SMYKLOT_COMMAND_ALIASES: >-
          ${{
            inputs.command-aliases ||
            env.SMYKLOT_COMMAND_ALIASES ||
            steps.parse-config.outputs.command_aliases
          }}
        SMYKLOT_COMMAND_PREFIX: >-
          ${{
            inputs.command-prefix ||
            env.SMYKLOT_COMMAND_PREFIX ||
            steps.parse-config.outputs.command_prefix
          }}
        SMYKLOT_DISABLE_MENTIONS: >-
          ${{
            inputs.disable-mentions ||
            env.SMYKLOT_DISABLE_MENTIONS ||
            steps.parse-config.outputs.disable_mentions
          }}
      run: ${{ runner.temp }}/smyklot-github-action
