name: Smyklot PR Commands
description: GitHub Actions bot for automated PR approvals and merges based on CODEOWNERS
author: Bart Smykla

branding:
  icon: check-circle
  color: green

inputs:
  token:
    description: GitHub token for API authentication
    required: false
    default: ''
  comment-body:
    description: PR comment body text
    required: false
    default: ''
  comment-id:
    description: PR comment ID
    required: false
    default: ''
  pr-number:
    description: Pull request number
    required: false
    default: ''
  repo-owner:
    description: Repository owner
    required: false
    default: ''
  repo-name:
    description: Repository name
    required: false
    default: ''
  comment-author:
    description: Comment author username
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: ${{ github.action_path }}/go.mod
        cache-dependency-path: ${{ github.action_path }}/go.sum

    - name: Build smyklot binary
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go build -o ${{ runner.temp }}/smyklot-github-action ./cmd/github-action

    - name: Execute command
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token || env.GITHUB_TOKEN }}
        COMMENT_BODY: ${{ inputs.comment-body || env.COMMENT_BODY }}
        COMMENT_ID: ${{ inputs.comment-id || env.COMMENT_ID }}
        PR_NUMBER: ${{ inputs.pr-number || env.PR_NUMBER }}
        REPO_OWNER: ${{ inputs.repo-owner || env.REPO_OWNER }}
        REPO_NAME: ${{ inputs.repo-name || env.REPO_NAME }}
        COMMENT_AUTHOR: ${{ inputs.comment-author || env.COMMENT_AUTHOR }}
      run: ${{ runner.temp }}/smyklot-github-action
