name: 'Smyklot'
description: 'Automated PR approvals and merges based on CODEOWNERS permissions'
author: 'Bart Smykla'

branding:
  icon: 'zap'
  color: 'purple'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/smykla-labs/smyklot:1.9.2'
