on: [push]

name: CI/CD

jobs:
  build_image:
    name: "Build and push container image"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: "Docker Layer Cache"
      uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: "Set up QEMU"
      uses: docker/setup-qemu-action@v1
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v1
    - name: "Prepare variables"
      id: vars
      run: |
        VERSION="$(cargo read-manifest | jq -r '.version')"

        TAGS="ghcr.io/${{ github.repository }}:${VERSION}"
        if [[ $GITHUB_REF == ref/head/master ]]; then
          TAGS="$TAGS,ghcr.io/${{ github.repository }}:latest"
        fi
        
        echo ::set-output name=tags::${TAGS}
    - name: "Build and push"
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: ${{ steps.vars.outputs.tags }}
    - name: "Image digest"
      run: echo ${{ steps.docker_build.outputs.digest }}
      
  bump_version:
    needs: build_image
    name: "Bump Version and create Tag"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-bump
          key: ${{ runner.os }}-cargo-bumb-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Install cargo-bump"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bump
      - name: "Bump Cargo version and create a git tag"
        uses: actions-rs/cargo@v1
        with:
          command: bump
          args: patch
      - name: "Regenerate Cargo.lock file"
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: "Save version to output"
        id: vars
        run: echo ::set-output name=version::$(cargo read-manifest | jq '.version')
      - name: "Commit bumped version"
        uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Bump version to: ${{ steps.vars.outputs.version }} "
          add: "Cargo.toml Cargo.lock"
          tag: "${{ steps.vars.outputs.version }}"
