on: [push]

name: CI/CD

jobs:
  build_and_deploy:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Install Cargo RPM"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-rpm
      - name: "Build RPM"
        uses: actions-rs/cargo@v1
        with:
          command: rpm
          args: build -v
      - name: "Copy RPMs to the server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "target/release/rpmbuild/RPMS/x86_64/*.rpm"
          target: "~/"
          strip_components: 6
      - name: "Install doctl"
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: "Install RPM"
        run: |
          TMP_PATH="$(mktemp)"; \
          echo "${{ secrets.KEY }}" > "$TMP_PATH"; \
          doctl compute ssh \
            --ssh-user ${{ secrets.USERNAME }} \
            --ssh-key-path "$TMP_PATH" \
            --ssh-command "sudo yum localinstall -y ~/*.rpm" \
            smyklot
