on: [push]

name: CI/CD

jobs:
  build_and_deploy:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Install cargo-bump"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bump
      - name: "Bump Cargo version and create a git tag"
        uses: actions-rs/cargo@v1
        with:
          command: bump
          args: minor --git-tag
      - name: "Commit bumped version"
        uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Bump version"
          add: "Cargo.toml"
